from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QHeaderView


class Ui_Game(object):
    def setupUi(self, Game):
        Game.setObjectName("Game")
        Game.resize(554, 399)
        Game.setDocumentMode(False)
        Game.setTabShape(QtWidgets.QTabWidget.Rounded)
        Game.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.centralwidget = QtWidgets.QWidget(Game)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.level_progress_layout = QtWidgets.QHBoxLayout()
        self.level_progress_layout.setObjectName("level_progress_layout")
        self.level_progress_label = QtWidgets.QLabel(self.centralwidget)
        self.level_progress_label.setObjectName("level_progress_label")
        self.level_progress_label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.level_progress_layout.addWidget(self.level_progress_label)
        self.level_progress = QtWidgets.QProgressBar(self.centralwidget)
        self.level_progress.setProperty("value", 0)
        self.level_progress.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.level_progress.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.level_progress.setObjectName("level_progress")
        self.level_progress_layout.addWidget(self.level_progress)
        self.verticalLayout_2.addLayout(self.level_progress_layout)
        self.stats_layout = QtWidgets.QHBoxLayout()
        self.stats_layout.setObjectName("stats_layout")
        self.score_layout = QtWidgets.QVBoxLayout()
        self.score_layout.setObjectName("score_layout")
        self.score_label = QtWidgets.QLabel(self.centralwidget)
        self.score_label.setAutoFillBackground(False)
        self.score_label.setStyleSheet("font: 75 15pt \"MS Shell Dlg 2\";")
        self.score_label.setAlignment(QtCore.Qt.AlignCenter)
        self.score_label.setObjectName("score_label")
        self.score_layout.addWidget(self.score_label)
        self.score_number = QtWidgets.QLCDNumber(self.centralwidget)
        self.score_number.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.score_number.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.score_number.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.score_number.setObjectName("score_number")
        self.score_layout.addWidget(self.score_number, 0, QtCore.Qt.AlignHCenter)
        self.stats_layout.addLayout(self.score_layout)
        self.level_layout = QtWidgets.QVBoxLayout()
        self.level_layout.setObjectName("level_layout")
        self.curent_level_label = QtWidgets.QLabel(self.centralwidget)
        self.curent_level_label.setObjectName("curent_level_label")
        self.curent_level_label.setStyleSheet("font: 75 15pt \"MS Shell Dlg 2\";")
        self.level_layout.addWidget(self.curent_level_label, 0, QtCore.Qt.AlignHCenter)
        self.level_number = QtWidgets.QLabel(self.centralwidget)
        self.level_number.setObjectName("level_number")
        self.level_number.setStyleSheet("font: 75 15pt \"MS Shell Dlg 2\";")
        self.level_layout.addWidget(self.level_number, 0, QtCore.Qt.AlignHCenter)
        self.stats_layout.addLayout(self.level_layout)
        self.record_layout = QtWidgets.QVBoxLayout()
        self.record_layout.setObjectName("record_layout")
        self.record_label = QtWidgets.QLabel(self.centralwidget)
        self.record_label.setAlignment(QtCore.Qt.AlignCenter)
        self.record_label.setStyleSheet("font: 75 15pt \"MS Shell Dlg 2\";")
        self.record_label.setObjectName("record_label")
        self.record_layout.addWidget(self.record_label)
        self.record_number = QtWidgets.QLCDNumber(self.centralwidget)
        self.record_number.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.record_number.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.record_number.setMidLineWidth(0)
        self.record_number.setSmallDecimalPoint(False)
        self.record_number.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.record_number.setObjectName("record_number")
        self.record_layout.addWidget(self.record_number, 0, QtCore.Qt.AlignHCenter)
        self.stats_layout.addLayout(self.record_layout)
        self.verticalLayout_2.addLayout(self.stats_layout)
        self.game_field = QtWidgets.QTableView(self.centralwidget)
        self.game_field.setObjectName("game_field")
        self.game_field.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.game_field.horizontalHeader().setVisible(False)
        self.game_field.horizontalHeader().setCascadingSectionResizes(False)
        self.game_field.horizontalHeader().setDefaultSectionSize(50)
        self.game_field.verticalHeader().setVisible(False)
        self.game_field.verticalHeader().setCascadingSectionResizes(False)
        self.game_field.verticalHeader().setDefaultSectionSize(50)
        self.game_field.verticalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.game_field.horizontalHeader().setMinimumSectionSize(24)
        self.game_field.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.verticalLayout_2.addWidget(self.game_field)
        Game.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Game)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 554, 18))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        Game.setMenuBar(self.menubar)
        self.actionNew_game = QtWidgets.QAction(Game)
        self.actionNew_game.setObjectName("actionNew_game")
        self.actionSettings = QtWidgets.QAction(Game)
        self.actionSettings.setObjectName("actionSettings")
        self.actionExit = QtWidgets.QAction(Game)
        self.actionExit.setObjectName("actionExit")
        self.menu.addAction(self.actionNew_game)
        self.menu.addSeparator()
        self.menu.addAction(self.actionSettings)
        self.menu.addSeparator()
        self.menu.addAction(self.actionExit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(Game)
        QtCore.QMetaObject.connectSlotsByName(Game)

    def retranslateUi(self, Game):
        _translate = QtCore.QCoreApplication.translate
        Game.setWindowTitle(_translate("Game", "Game"))
        self.level_progress_label.setText(_translate("Game", "Level progress:"))
        self.score_label.setText(_translate("Game", "Score"))
        self.curent_level_label.setText(_translate("Game", "Current level"))
        self.record_label.setText(_translate("Game", "Record"))
        self.menu.setTitle(_translate("Game", "Menu"))
        self.actionNew_game.setText(_translate("Game", "New game"))
        self.actionSettings.setText(_translate("Game", "Settings"))
        self.actionExit.setText(_translate("Game", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Game = QtWidgets.QMainWindow()
    ui = Ui_Game()
    ui.setupUi(Game)
    Game.show()
    sys.exit(app.exec_())
